#整个配置文件的组入口
[Menu Entry]  																
#该.conf文件的相关描述
Comment=百度网盘的右键配置文件
#对应语言_地区下该.conf文件的描述,这里对应的是中文
Comment[zh_CN]=百度网盘的右键配置文件
#该配置文件采用的规范协议版本
Version=1.0
#在[Menu Entry]下包含另外有2个分组,入口名对应为ActionOne和ActionTwo且作为一级菜单
Actions=ActionUpload

#[Menu Entry] 中对应的Action分组, 作为一级菜单,同理一级菜单分组中指明的分组就作为二级菜单
[Menu Action ActionUpload] 											  					
#项目的特定名称:一级菜单1,同样作为未找到对应区域的情况下兜底使用
Name=上传到百度网盘
#对应区域语言的特定名称:一级菜单1,用户自定义修改的名字就是替换此，处对应区域语言的名字
Name[en]=Upload to Baidu Netdisk
Name[en_us]=Upload to Baidu Netdisk
Name[en_gb]=Upload to Baidu Netdisk
Name[az]=Baidu diskinə yüklə
Name[ca]=Enlever sur le disque en ligne de Baidu
Name[de]=Laden Sie auf Baidu Online-Disk hoch
Name[es]=Subir a Baidu netdisk
Name[fi]=Lataa Baidu- verkkolevylle
Name[fr]=Télécharger sur le disque réseau Baidu
Name[hu]=Töltse fel Baidu online lemezre
Name[id]=Upload to Baidu netdisk
Name[it]=Carica sul disco online Baidu
Name[nl]=Upload naar Baidu netdisk
Name[pl]=Wyślij na dysk online Baidu
Name[pt]=Enviar para o disco online Baidu
Name[tr]=Baidu online diskine yükle
Name[zh_CN]=上传到百度网盘
Name[zh_HK]=上傳到百度網盤
Name[zh_TW]=上傳到百度網盤
#表示该插件功能仅在文件选择时生效
X-DFM-MenuTypes=SingleFile:SingleDir:MultiFiles:MultiDirs:FileAndDir
#执行动作
Exec=/opt/baidunetdisk/baidunetdisk --no-sandbox --menuupload %F
#默认在右键菜单的一级菜单的第二个位置插入该项
PosNum=2
#在该项的上方插入分割线
X-DFM-SupportSchemes=file
Separator=Top
